package tal

var htmlVoidElements = map[string]bool{
	"area":    true,
	"base":    true,
	"br":      true,
	"col":     true,
	"command": true,
	"embed":   true,
	"hr":      true,
	"img":     true,
	"input":   true,
	"keygen":  true,
	"link":    true,
	"meta":    true,
	"param":   true,
	"source":  true,
	"track":   true,
	"wbr":     true,
}

var htmlBooleanAttributes = map[string]bool{
	"allowFullscreen": true,
	"async":           true,
	"autofocus":       true,
	"autoplay":        true,
	"checked":         true,
	"compact":         true,
	"controls":        true,
	"declare":         true,
	"default":         true,
	"defaultChecked":  true,
	"defaultMuted":    true,
	"defaultSelected": true,
	"defer":           true,
	"disabled":        true,
	"draggable":       true,
	"enabled":         true,
	"formNoValidate":  true,
	"hidden":          true,
	"indeterminate":   true,
	"inert":           true,
	"isMap":           true,
	"itemScope":       true,
	"loop":            true,
	"multiple":        true,
	"muted":           true,
	"noHref":          true,
	"noResize":        true,
	"noShade":         true,
	"noValidate":      true,
	"noWrap":          true,
	"open":            true,
	"pauseOnExit":     true,
	"readOnly":        true,
	"required":        true,
	"reversed":        true,
	"scoped":          true,
	"seamless":        true,
	"selected":        true,
	"sortable":        true,
	"spellcheck":      true,
	"translate":       true,
	"trueSpeed":       true,
	"typeMustMatch":   true,
	"visible":         true,
}
